\c urban_notes;

create table todo (
    tid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id char(100),
    title varchar(512) NOT NULL,
    added timestamp NOT NULL DEFAULT now(),
    idemp_key varchar(32) NOT NULL
);

CREATE UNIQUE INDEX idx_todo_idemp ON todo (idemp_key);
CREATE UNIQUE INDEX idx_todo_user_added ON todo (user_id, tid);

create table sync_cursor (
    user_id char(100),
    agent_id char(16),
    last_tid integer NOT NULL DEFAULT 0,
    updated timestamp NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_sync_cursor_user_id_agent_id ON sync_cursor (user_id, agent_id);
